### PR TITLE
Bump to Fedora 33

### PR DESCRIPTION
**Pull request by skitt**
This gives us kubectl 1.19, which can handle clusters from 1.17 to
1.21.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]
seems to be good, why draft?

**Comment by skitt** [comment]
> seems to be good, why draft?

Fedora 33 hasn’t been released yet :-).

**Comment by mangelajo** [comment]
> > seems to be good, why draft?
> 
> Fedora 33 hasn’t been released yet :-).

oh right, it's beta at this point ':D

**Comment by dfarrell07** [comment]
It seems like the GH required checks config needs to be updated for Shipyard @mangelajo @skitt. :pray:

**Comment by skitt** [comment]
> Update: Or maybe they have been updated for #342 but that PR hasn't actually landed yet.

Yup, that’s one of the first things I did after becoming admin, with the idea that #342 would get in quickly.

**Comment by skitt** [comment]
https://fedoramagazine.org/announcing-fedora-33/

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
