### PR TITLE
Bump golangci-lint to 1.46.0

### PR DESCRIPTION
**Pull request by skitt**
See https://github.com/golangci/golangci-lint/releases/tag/v1.46.0

Depends on https://github.com/submariner-io/submariner/pull/1827
Depends on https://github.com/submariner-io/lighthouse/pull/756
Depends on https://github.com/submariner-io/submariner-operator/pull/2073
Depends on https://github.com/submariner-io/shipyard/pull/816
Depends on https://github.com/submariner-io/submariner-operator/pull/2079
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
@skitt do you want some help with these fixes?

**Comment by skitt** [comment]
> @skitt do you want some help with these fixes?

Thanks, the fixes were straightforward and hardly took any time ;-). I think this will be OK once the dependencies are merged.

**Comment by dfarrell07** [comment]
> I think this will be OK once the dependencies are merged.

There was one more fix in the operator that I sent/linked. Super late for you, so I assumed you were not working on it.

**Review by dfarrell07 — APPROVED** [review]

**Comment by skitt** [comment]
> > I think this will be OK once the dependencies are merged.
> 
> There was one more fix in the operator that I sent/linked. Super late for you, so I assumed you were not working on it.

Thanks!

**Pull request merged**
