### PR TITLE
Remove extraneous E2E args

### LINKED ISSUE #527: Remove script specific Makefile variables
There were some script specific Makefile variables added recently:

https://github.com/submariner-io/shipyard/blob/devel/Makefile.inc#L54-L69

We have, long ago, decided against having script specific make variables. In this regard, this change is a regression.
In addition, having these script options redefined as make variables, whereas other options aren't, is very inconsistent.

Instead of having and using these script specific variables, use the general `*_ARGS` variables i.e. `E2E_ARGS`

### PR DESCRIPTION
**Pull request by mkolesnik**
These shouldn't be `Makefile` args or GHA inputs, we already have a mechanism to specify such args with `using` and the various `*_E2E` args.

Resolves: #527 
Depends on: https://github.com/submariner-io/submariner/pull/1458

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
@manosnoam You're not using these Ginkgo options through this tooling, right?

**Comment by dfarrell07** [comment]
@mkimuram Are you using these args?

**Comment by mkimuram** [comment]
`plugin` and `testdir` are used [here](https://github.com/submariner-io/submariner/blob/devel/.github/workflows/e2e-external.yml#L18) in GHA. `focus` and `skip` are expected to be used manually on running `make e2e` from command line for local test/debug.

**Comment by dfarrell07** [comment]
Thanks for the info @mkimuram! 

> `plugin` and `testdir` are used [here](https://github.com/submariner-io/submariner/blob/devel/.github/workflows/e2e-external.yml#L18) in GHA.

@mkolesnik has a PR to migrate these to `using=`: https://github.com/submariner-io/submariner/pull/1458

> `focus` and `skip` are expected to be used manually on running `make e2e` from command line for local test/debug.

Sounds like we should do your suggestion of adding them "as proper 'ginkgo args' should such a
feature be desired" @mkolesnik?

**Comment by mkolesnik** [comment]
> `plugin` and `testdir` are used [here](https://github.com/submariner-io/submariner/blob/devel/.github/workflows/e2e-external.yml#L18) in GHA. `focus` and `skip` are expected to be used manually on running `make e2e` from command line for local test/debug.

Expected is one thing, question is if anyone is actually using them.

I prefer to add things that are actively used and not maintain them just for sake of "maybe they'll be used".

**Comment by mkimuram** [comment]
> Expected is one thing, question is if anyone is actually using them.

Personally, I actually use them. It is helpful in testing only related tests or added tests, locally.

However, I will wait for reply from other people on whether using or planning to use it. Note that at least `focus` was in [submarier-io/submariner](https://github.com/submariner-io/submariner/commit/1b2511d66d511172266e2e3a8260a89e3ad37393) before my commit.

**Comment by mkimuram** [comment]
FYI: ginkgo's skip and focus are effectively used in k8s's CI, by adding `[slow]` or `[disruptive]` tags in test specs and making them in separate CI jobs. These jobs run only on related PR or periodically, not on all PRs. It's not currently utilized in such a way in submariner's project, however it will be worth considering.

**Pull request closed without merging**
