### PR TITLE
Specify --natt=false instead of --disable-nat

### PR DESCRIPTION
**Pull request by skitt**
The latter is deprecated and results in a warning in the logs.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Comment by skitt** [comment]
0.8 doesn’t know about `--natt` so we can’t test upgrades with this. This will have to wait until after the 0.9 release.

**Comment by nyechiel** [comment]
Still relevant, adding to the 0.10 board.

**Comment by skitt** [comment]
Still relevant.

**Comment by nyechiel** [comment]
Not sure why this was closed, reopening.

**Comment by tpantelis** [comment]
bump

**Review by nyechiel — APPROVED** [review]

**Pull request merged**
