### PR TITLE
Revert "Update shflags 1.0.3 to 1.2.3"

### PR DESCRIPTION
**Pull request by dfarrell07**
This reverts commit 264c1e7dad11d271c60e7a8f4368076cec881334.

### CODE REVIEW

**Comment by dfarrell07** [comment]
I'm testing if this is needed. Some jobs failed on the last run of https://github.com/submariner-io/shipyard/pull/732, but because they were not required it auto-merged.

**Comment by skitt** [comment]
> I'm testing if this is needed. Some jobs failed on the last run of #732, but because they were not required it auto-merged.

This doesn’t show up in jobs, it shows up when we try to release the images after a PR is merged. To see this locally, run `docker login` then `make shell` and try `docker login` again inside the Dapper container.

I have a potentially better fix coming up for this...

**Comment by dfarrell07** [comment]
I think this is needed, right @skitt?

Most of the E2E Consuming jobs failed on the last run of the original:

https://github.com/submariner-io/shipyard/runs/5362334989?check_suite_focus=true

And are passing with the revert:

https://github.com/submariner-io/shipyard/runs/5362593481?check_suite_focus=true

**Comment by dfarrell07** [comment]
I'm running the E2E Consuming on current devel again here: https://github.com/dfarrell07/shipyard/pull/34

**Comment by dfarrell07** [comment]
> I'm running the E2E Consuming on current devel again here: [dfarrell07#34](https://github.com/dfarrell07/shipyard/pull/34)

Yeah these are failing in the same way, so I do think we should merge this quickly.

**Review by skitt — APPROVED** [review]

**Comment by dfarrell07** [comment]
Sorry for the auto-merge of the original, all! I wanted to show "let's merge this next, it has a huge set of jobs to re-run". I was watching the jobs, but the required ones finished quickly and it merged before any started failing.

**Review by Billy99 — APPROVED** [review]

**Pull request merged**
