### PR TITLE
fix: sync helm charts values

### PR DESCRIPTION
**Pull request by SteveMattar**
Signed-off-by: Steve Mattar <smattar@redhat.com>

### CODE REVIEW

**Comment by SteveMattar** [comment]
Merge after https://github.com/submariner-io/submariner-charts/pull/125

**Comment by tpantelis** [comment]
> Merge after [submariner-io/submariner-charts#125](https://github.com/submariner-io/submariner-charts/pull/125)

Let's make it a draft in the meantime.

**Review by dfarrell07 — APPROVED** [review]
I think this is what we need to fix the Globalnet+Helm issue we talked about today @skitt @sridhargaddam @mangelajo @tpantelis.

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
Thanks @tpantelis! I'm re-running the jobs out of an abundance of caution before merging.

**Pull request merged**
