### PR TITLE
Bump golangci-lint to 1.50.1

### PR DESCRIPTION
**Pull request by skitt**
Changes since 1.47.3:
* https://github.com/golangci/golangci-lint/releases/tag/v1.48.0
* https://github.com/golangci/golangci-lint/releases/tag/v1.49.0
* https://github.com/golangci/golangci-lint/releases/tag/v1.50.0
* https://github.com/golangci/golangci-lint/releases/tag/v1.50.1

Depends on https://github.com/submariner-io/subctl/pull/375
Depends on https://github.com/submariner-io/admiral/pull/461
Depends on https://github.com/submariner-io/cloud-prepare/pull/465
Depends on https://github.com/submariner-io/lighthouse/pull/960
Depends on https://github.com/submariner-io/subctl/pull/379
Depends on https://github.com/submariner-io/submariner/pull/2127
Depends on https://github.com/submariner-io/submariner-operator/pull/2353
Depends on https://github.com/submariner-io/submariner/pull/2147

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Testing enabling the new linters from these versions here: https://github.com/dfarrell07/shipyard/pull/48

**Comment by skitt** [comment]
We should postpone this until after rc0, there’s quite a lot of work involved.

**Comment by dfarrell07** [comment]
Maybe I can send some of the simpler fixes before the RC so we don't have to backport them? A lot of the issues seem related to spacing of nolint directives.

**Comment by skitt** [comment]
> Maybe I can send some of the simpler fixes before the RC so we don't have to backport them? A lot of the issues seem related to spacing of nolint directives.

I’ve scripted that one ;-).

**Comment by skitt** [comment]
@dfarrell07, @tpantelis, this is ready to go.

**Review by tpantelis — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]

**Pull request merged**
