### PR TITLE
Bump golangci-lint to 1.39.0

### PR DESCRIPTION
**Pull request by skitt**
Changes:
* https://github.com/golangci/golangci-lint/releases/tag/v1.37.0
* https://github.com/golangci/golangci-lint/releases/tag/v1.37.1
* https://github.com/golangci/golangci-lint/releases/tag/v1.38.0
* https://github.com/golangci/golangci-lint/releases/tag/v1.39.0

Significant changes:
* Go 1.16 support
* New linters (some already covered by other linters):
  - cyclop (cyclomatic complexity)
  - duration check (multiplication of time values)
  - ForceTypeAssert (unchecked type assertions)
  - gomoddirectives (replace/retract/exclude checks for go.mod)
  - ifaceassert (conflicting interface assertions)
  - nilerr (inconsistent returns after error checks)
  - revive (yet another golint replacement)
  - stringintconv (probably invalid string-to-int conversions)
  - wastedassign (unused assignments)
* Deprecated linters:
  - Interfacer
  - maligned, replaced by fieldalignment
  - scopelint, replaced by looppointer or exportloopref

Depends on: https://github.com/submariner-io/submariner-operator/pull/1238
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
This breaks the operator:

```
controllers/servicediscovery/servicediscovery_controller_test.go:35:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated: please use pkg/envtest for testing. This package will be dropped before the v1.0.0 release. Package fake provides a fake client for testing. (staticcheck)
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	^
controllers/submariner/submariner_controller_test.go:39:2: SA1019: package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated: please use pkg/envtest for testing. This package will be dropped before the v1.0.0 release. Package fake provides a fake client for testing. (staticcheck)
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	^
```

**Review by mangelajo — APPROVED** [review]

**Comment by dfarrell07** [comment]
https://github.com/submariner-io/submariner-operator/pull/1238 is merged, re-running consuming project linting.

**Review by dfarrell07 — APPROVED** [review]
All passing now, thanks @skitt!

Re-making-note of https://github.com/submariner-io/submariner-operator/issues/1236 for the longer-term.

**Comment by dfarrell07** [comment]
This impacts us I think:

> maligned, replaced by fieldalignment

Raised https://github.com/submariner-io/submariner/issues/1252 to track.

**Pull request merged**
