### PR TITLE
Use BuildKit to build the images

### PR DESCRIPTION
**Pull request by skitt**
This greatly improves caching in my experience. See
https://docs.docker.com/engine/reference/builder/#buildkit and
https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources
for details.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Seems like a real error?

https://github.com/submariner-io/shipyard/pull/248/checks?check_run_id=842076084#step:3:102

**Comment by skitt** [comment]
> Seems like a real error or something intermittent?
> 
> https://github.com/submariner-io/shipyard/pull/248/checks?check_run_id=842076084#step:3:102

Something intermittent, it’s a download error on metadata coming from Fedora, nothing to do with us (and nothing we can do anything about, unfortunately, unless we split out the Fedora parts of the image).

**Comment by mangelajo** [comment]
```
# Rebuild the image to update any changed layers and tag it back so it will be used.
<<<<<<< buildkit
DOCKER_BUILDKIT=1 docker build -t ${local_image} ${cache_flag} -f ${dockerfile} --build-arg BUILDKIT_INLINE_CACHE=1 .
docker tag ${local_image} ${latest_image}
=======
buildargs_flag=''
[[ -z "${buildargs}" ]] || buildargs_flag="--build-arg ${buildargs}"
docker build -t ${local_image} ${cache_flag} -f ${dockerfile} ${buildargs_flag} .
docker tag ${local_image} ${cache_image}

>>>>>>> master
```
This conflicts now, I wonder if we can pass --build-arg multiple times?

**Comment by skitt** [comment]
The PR fails gitlint because of the URL... @dfarrell07 what would you recommend? I think the URL is useful to have (and not via a URL shortener).

**Review by mangelajo — APPROVED** [review]

**Review by dfarrell07 — DISMISSED** [review]
+1 to the use of gitlint-ignore in this case.

**Review by mangelajo — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
