### PR TITLE
Update Feature multi active gw branch with Devel

### PR DESCRIPTION
**Pull request by astoycos**
To pull in fix for broken nginx image pulls.

### CODE REVIEW

**Review by Billy99 — APPROVED** [review]

**Review by anfredette — APPROVED** [review]
LGTM

**Comment by astoycos** [comment]
Hrm we need to make 

`Shared Scripts / Deploy (ovn) (pull_request) `
and 
`Linting / Commit Message(s) (pull_request)`

Optional on this feature branch (like it they are on devel) as well... @dfarrell07 Can you help with that possibly, I'm not 100% sure how to do it...I think it's a gui settings option that I can't see?

**Comment by anfredette** [comment]
> Hrm we need to make
> 
> `Shared Scripts / Deploy (ovn) (pull_request) ` and `Linting / Commit Message(s) (pull_request)`
> 
> Optional on this feature branch (like it they are on devel) as well... @dfarrell07 Can you help with that possibly, I'm not 100% sure how to do it...I think it's a gui settings option that I can't see?

@tpantelis @sridhargaddam Can either of you help with the above request?  Andrew is just trying to update this branch to match devel.  Thanks, Andre

**Comment by tpantelis** [comment]
> @tpantelis @sridhargaddam Can either of you help with the above request? Andrew is just trying to update this branch to match devel. Thanks, Andre

Done

**Comment by anfredette** [comment]
> Done

Thanks!

**Pull request merged**
