### PR TITLE
Fix yamllint strict config, fail on warnings

### PR DESCRIPTION
**Pull request by dfarrell07**
Setting yamllint to exit non-zero on warnings doesn't work from the
.yamllint config file. Set the --strict flag at CLI invocation.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
We shouldn't merge this until the YAML warnings are fixed in all repos.

**Comment by dfarrell07** [comment]
It's a good sign that this is now (correctly) failing the Linting/YAML job, FYI.

**Comment by dfarrell07** [comment]
> It's a good sign that this is now (correctly) failing the Linting/YAML job, FYI.

The warnings will be fixed by https://github.com/submariner-io/shipyard/pull/629.

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
This will fix the failing CI: https://github.com/submariner-io/shipyard/pull/631

**Comment by dfarrell07** [comment]
> This will fix the failing CI: #631

That was to fix the MD linting, this will fix the YAML linting: https://github.com/submariner-io/submariner-operator/pull/1551

**Comment by dfarrell07** [comment]
I think the warnings this will turn into failures are all fixed in consuming projects, so this can be merged. The failing consuming project linting jobs will be fixed by the PRs above, and are not related to this PR.

**Comment by dfarrell07** [comment]
For docs purposes, before I re-run CI, this is the current failure in `Consuming Projects / Lint (submariner-operator) (pull_request)`.

```
 <snip many more>
apis/vendor/k8s.io/klog/v2/README.md:89:1 MD010/no-hard-tabs Hard tabs [Column: 1]
apis/vendor/k8s.io/klog/v2/README.md:91:1 MD010/no-hard-tabs Hard tabs [Column: 1]
apis/vendor/k8s.io/klog/v2/README.md:93 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
make: *** [/opt/shipyard/Makefile.inc:145: markdownlint] Error 1
```

(Update: and it's still failing the same way, which is good)

**Review by tpantelis — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Review by Jaanki — APPROVED** [review]

**Pull request merged**
