### PR TITLE
Add support for Kubernetes 1.23

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Review by nyechiel — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by dfarrell07** [comment]
SHAs can be verified here: https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
Would you like me to raise an issue to track adding K8s 1.23 to the parts of CI that run multiple K8s versions? I can think of:

https://github.com/submariner-io/submariner-operator/blob/devel/.github/workflows/e2e-full.yml
https://github.com/submariner-io/submariner-operator/blob/devel/.github/workflows/flake_finder.yml

And maybe

https://github.com/submariner-io/submariner/blob/devel/.github/workflows/e2e-full.yml

**Comment by skitt** [comment]
We need to have a broader discussion about the versions of Kubernetes we want to test against. 1.23 is the latest release, and since it’s been released, 1.19 and 1.20 are no longer supported; so we could stop testing those...

See https://github.com/submariner-io/submariner-website/issues/624

**Comment by dfarrell07** [comment]
> We need to have a broader discussion about the versions of Kubernetes we want to test against. 1.23 is the latest release, and since it’s been released, 1.19 and 1.20 are no longer supported; so we could stop testing those...
> 
> See [submariner-io/submariner-website#624](https://github.com/submariner-io/submariner-website/issues/624)

We've established a set of TODOs around K8s versions here: https://github.com/submariner-io/submariner-website/issues/624#issuecomment-992808761

**Pull request merged**
