### PR TITLE
Remove `shflags` entirely

### PR DESCRIPTION
**Pull request by mkolesnik**
Now that consuming projects have been updated, we can get rid of shflags
and use ENV variables across the board.

Depends on https://github.com/submariner-io/coastguard/pull/69
Depends on https://github.com/submariner-io/submariner-charts/pull/248
Depends on https://github.com/submariner-io/releases/pull/452
Depends on https://github.com/submariner-io/admiral/pull/390
Depends on https://github.com/submariner-io/lighthouse/pull/839
Depends on https://github.com/submariner-io/subctl/pull/188
Depends on https://github.com/submariner-io/subctl/pull/200
Depends on https://github.com/submariner-io/submariner-operator/pull/2159
Depends on https://github.com/submariner-io/submariner/pull/1942

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
>Shared Scripts / Compile

```
The binary and source must be sepcified!
[01:35:59.682] [shipyard]$ test/scripts/compile/test.sh
make: *** [Makefile:62: script-test] Error 1
```

**Comment by skitt** [comment]
> > Shared Scripts / Compile
> 
> ```
> The binary and source must be sepcified!
> [01:35:59.682] [shipyard]$ test/scripts/compile/test.sh
> make: *** [Makefile:62: script-test] Error 1
> ```

There’s a stray `--noupx` in `test/scripts/compile/test.sh`.

**Review by skitt — APPROVED** [review]

**Comment by mkolesnik** [comment]
> There’s a stray `--noupx` in `test/scripts/compile/test.sh`.

Yes it was from #895, I updated the tests

**Comment by dfarrell07** [comment]
```
/opt/shipyard/scripts/compile.sh \
	--ldflags "-X 'github.com/submariner-io/subctl/pkg/version.Version=devel-e7ef668' \
	       -X 'github.com/submariner-io/submariner-operator/api/submariner/v1alpha1.DefaultSubmarinerOperatorVersion=${DEFAULT_IMAGE_VERSION#v}' \
	       -X 'github.com/submariner-io/submariner-operator/api/submariner/v1alpha1.DefaultRepo="quay.io/submariner"'" \
        --noupx cmd/bin/subctl-devel-e7ef668-linux-amd64 ./cmd 
make[1]: *** [Makefile:110: cmd/bin/subctl-devel-e7ef668-linux-amd64] Error 1
The binary and source must be sepcified!
make[1]: Leaving directory '/go/src/github.com/submariner-io/subctl'
make: *** [/opt/shipyard/Makefile.inc:145: e2e] Error 2
```

**Comment by mkolesnik** [comment]
Yea, missed this one place in `subctl` :)

https://github.com/submariner-io/subctl/pull/200

Good thing we have tests :grin:

**Pull request merged**
