### PR TITLE
Import the right submariner gateway and latest images 

### PR DESCRIPTION
**Pull request by mangelajo**
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

**Review by nyechiel — APPROVED** [review]

**Review by SteveMattar — APPROVED** [review]

**Comment by mangelajo** [comment]
Dependent projects still fail because the shipyard go code needs to be updated in those repos after the submariner-gateway rename.

**Review by mkolesnik — CHANGES_REQUESTED** [review]
Let me suggest a different approach which i think would be better. I'll send a patch shortly

**Comment by mangelajo** [comment]
> Let me suggest a different approach which i think would be better. I'll send a patch shortly

ack, but let's be quick, we have to release M1 , we are 2 weeks late already.

If it starts to look complex or risky, please let's merge this one and improve it for M2

**Comment by mangelajo** [comment]
@nyechiel @SteveMattar  can you move votes to this one? https://github.com/submariner-io/shipyard/pull/465

**Comment by mkolesnik** [comment]
Propose #465 instead which offers a cleaner solution and can be used easily in consuming projects

**Comment by mangelajo** [comment]
Handled in https://github.com/submariner-io/shipyard/pull/465

**Pull request closed without merging**
