### PR TITLE
Bump golangci-lint to 1.36

### PR DESCRIPTION
**Pull request by skitt**
Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Wondering why the validate-projects jobs are being skipped.

> Consuming Projects / Lint (pull_request) Skipped

https://github.com/submariner-io/shipyard/pull/429/checks?check_run_id=1785480952

**Comment by dfarrell07** [comment]
Ah, because the label need to be updated to 'lint-projects' (I thought I did this?).

https://github.com/submariner-io/shipyard/blob/master/.github/workflows/consuming.yml#L69

**Comment by skitt** [comment]
> Ah, because the label need to be updated to 'lint-projects' (I thought I did this?).
> 
> https://github.com/submariner-io/shipyard/blob/master/.github/workflows/consuming.yml#L69
> 
> Edit: I think I was seeing a GH glitch. It was showing this as labeled `validate-projects` until I went and tried to add `lint-projects` and failed on a warning that label already exists (even though I double checked it didn't, both here and on the edit labels page).

That’s probably because I renamed the label while you were adding this comment ;-).

**Review by dfarrell07 — APPROVED** [review]

**Comment by skitt** [comment]
Submariner linting should be fixed by https://github.com/submariner-io/submariner/pull/1117

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
