### PR TITLE
Bump to kind 0.20.0

### PR DESCRIPTION
**Pull request by skitt**
This adds support for Kubernetes 1.28.

Depends on https://github.com/ovn-org/ovn-kubernetes/pull/4015

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Comment by dfarrell07** [comment]
[Deployment (ovn)](https://github.com/submariner-io/shipyard/actions/runs/5478343793/jobs/9978747853?pr=1297#logs) failed, re-running.

**Comment by dfarrell07** [comment]
[Deployment (ovn)](https://github.com/submariner-io/shipyard/actions/runs/5478343793/jobs/10004465038?pr=1297#logs) failed again.

**Comment by dfarrell07** [comment]
[Deployment (ovn)](https://github.com/submariner-io/shipyard/actions/runs/5478343793/jobs/10044448007?pr=1297#logs) failed again, seems to be consistent.

**Comment by sridhargaddam** [comment]
@aswinsuryan the OVN cluster deployment seems to be failing. Do you have any idea of the recent changes in OVN repo?

```
2023-07-28T12:39:25.4713041Z [cluster2] Deleted nodes: ["cluster2-worker" "cluster2-worker2" "cluster2-control-plane"]
2023-07-28T12:39:25.4713315Z [36m[12:39:24.909] [dir=shipyard; cl=cluster2; fn=delete_cluster_on_fail]$ return 1[0m
2023-07-28T12:39:25.4713569Z [cluster2] ERROR: Max attempts reached, failed to run 'provider_create_cluster'!
```

**Comment by tpantelis** [comment]
The OVN job consistently fails in this PR (oddly with very little output - seems to timeout) but didn't fail in the [dependabot bump PR](https://github.com/submariner-io/shipyard/pull/1333). The difference is that this PR updates the hashes in _scripts/shared/lib/clusters_kind_.

**Comment by aswinsuryan** [comment]
It may be solved when https://github.com/dfarrell07/shipyard/pull/55 goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.

**Comment by tpantelis** [comment]
> It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.

Ok but does that explain why the same job for https://github.com/submariner-io/shipyard/pull/1333 succeeds?

**Comment by dfarrell07** [comment]
> > It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.
> 
> Ok but does that explain why the same job for #1333 succeeds?

No, IMHO. Maybe it's something to do with the newer K8s versions introduced in this PR?

**Comment by aswinsuryan** [comment]
> > It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.
> 
> Ok but does that explain why the same job for #1333 succeeds?

oh that is strange , I would expect it to be same.

**Comment by tpantelis** [comment]
> > > It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.
> > 
> > 
> > Ok but does that explain why the same job for #1333 succeeds?
> 
> oh that is strange , I would expect it to be same.

This PR also updated the `kind` version hashes in _scripts/shared/lib/clusters_kind_ so I'm sure that's the reason. So something in the newer version is causing an issue with OVN.

**Comment by mkolesnik** [comment]
> Ok but does that explain why the same job for #1333 succeeds?

I might be wrong, but AFAICT the dependabot updates the go dependencies, while this one updated the actual K8s env that gets deployed, hence the first one is fine while this one clearly has some issues with OVN (which might get fixed with Daniel's patch)

> It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.

@dfarrell07 maybe based on this info we want to always rebuild the OVN image, not just on IC mode?

**Review by mkolesnik — APPROVED** [review]

**Comment by dfarrell07** [comment]
> > Ok but does that explain why the same job for #1333 succeeds?
> 
> I might be wrong, but AFAICT the dependabot updates the go dependencies, while this one updated the actual K8s env that gets deployed, hence the first one is fine while this one clearly has some issues with OVN (which might get fixed with Daniel's patch)
> 
> > It may be solved when [dfarrell07#55](https://github.com/dfarrell07/shipyard/pull/55) goes in. The OVN image we use is an old one as it does get update in quay for every PR merged in OVN. With this one we building image with latest code.
> 
> @dfarrell07 maybe based on this info we want to always rebuild the OVN image, not just on IC mode?

Maybe after the OVN IC PR goes in we can rebase this to test it with both the rebuilt and old images.

**Comment by dfarrell07** [comment]
I think we need an owner to rebase this and resolve the conflicts to see it run with both the rebuilt OVN image and the old one.

**Comment by tpantelis** [comment]
> I think we need an owner to rebase this and resolve the conflicts to see it run with both the rebuilt OVN image and the old one.

I rebased but it still fails.

**Comment by skitt** [comment]
> > Ok but does that explain why the same job for #1333 succeeds?
> 
> I might be wrong, but AFAICT the dependabot updates the go dependencies, while this one updated the actual K8s env that gets deployed, hence the first one is fine while this one clearly has some issues with OVN (which might get fixed with Daniel's patch)

Since #1302, the Go dependencies determine the versions of tools we use (the idea being that dependabot then keeps track of updates for us). So #1333 also changes the version of kind deployed in the environment. Without the hash changes however, the k8s images being deployed don’t change. I haven’t checked in detail what the actual changes are, but as a general rule we’re supposed to use the hashes given with each kind release (because images are often rebuilt to handle changes in kind itself).

**Comment by dfarrell07** [comment]
We're still seeing weirdness with OVN CI (K8s networkplugin doesn't come up).

**Comment by Jaanki** [comment]
@aswinsuryan Can you please take a look at this one on priority. We need it to start testing k8s 1.28.

**Comment by aswinsuryan** [comment]
The ovn-kube-node pod fails to come up due to this error. 

`2798 ovnkube.go:136] failed to start node network manager: failed to start default node network controller: failed to create IPTablesHelper for proto 0: could not get iptables version: exit status 127`

It works fine with `1.26.3` but not with `kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb`. This requires a fix in ovn-kubernetes.

**Comment by skitt** [comment]
@aswinsuryan thanks for the investigation! Do you know what the fix needs to be? I haven’t found a difference between the 1.26.3 and 1.26.6 images which would explain the change in behaviour...

**Comment by skitt** [comment]
Ah, https://github.com/ovn-org/ovn-kubernetes/pull/4015

**Comment by skitt** [comment]
I bumped ovn-kubernetes to the tip of the main branch, with the `iptables` fix, but it’s still failing to deploy (and I’ve run out of time to look into this, I’ll loop back next week unless someone else figures it out).

**Comment by aswinsuryan** [comment]
> ll loop back next week unless someone else figures it out).

Now it is failing at, 

`./daemonset.sh: line 824: openssl: command not found` (ovn-kubernetes/dist/images/daemonset.sh)

we use the `-ric `(run-in-container) option and seems like the container where it runs has the command missing. 

Adding this (in scripts/shared/lib/clusters_kind) solves it, but not sure if it is something we want to do

`delete_cluster_on_fail ./ovn-kubernetes/contrib/kind.sh -ov "$OVN_IMAGE" -cn "${KIND_CLUSTER_NAME}" -ric "${ovn_flags[@]}" -lr -dd "${KIND_CLUSTER_NAME}.local" --disable-ovnkube-identity`

**Comment by skitt** [comment]
> Adding this (in scripts/shared/lib/clusters_kind) solves it, but not sure if it is something we want to do
> 
> `delete_cluster_on_fail ./ovn-kubernetes/contrib/kind.sh -ov "$OVN_IMAGE" -cn "${KIND_CLUSTER_NAME}" -ric "${ovn_flags[@]}" -lr -dd "${KIND_CLUSTER_NAME}.local" --disable-ovnkube-identity`

Adding `--disable-ovnkube-identity` disables https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/node-identity.md which doesn’t seem to be a problem for tests.

**Pull request merged**
