### PR TITLE
Bump to Fedora 41

### PR DESCRIPTION
**Pull request by skitt**
This provides Go 1.23.

Compared to Fedora 40 images, this reduces the shipyard-dapper-base image size from 775MiB to 723MiB. Only installing the QEMU binaries that are needed further reduces that to 664MiB.

### CODE REVIEW

**Comment by skitt** [comment]
Fedora 41 is still in beta so this might not be advisable right now but the risk should be low.

**Comment by tpantelis** [comment]
> Fedora 41 is still in beta so this might not be advisable right now but the risk should be low.

Do you feel confident to merge this for RC0 on Mon?

**Comment by skitt** [comment]
> > Fedora 41 is still in beta so this might not be advisable right now but the risk should be low.
> 
> Do you feel confident to merge this for RC0 on Mon?

If we don’t need Go 1.23 for rc0, probably not.

**Comment by tpantelis** [comment]
> > > Fedora 41 is still in beta so this might not be advisable right now but the risk should be low.
> > 
> > 
> > Do you feel confident to merge this for RC0 on Mon?
> 
> If we don’t need Go 1.23 for rc0, probably not.

We don't - let's hold off.

**Comment by skitt** [comment]
Fedora 41 has been released.

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Pull request merged**
