### PR TITLE
Upgrade to Kubernetes 1.15

### PR DESCRIPTION
**Pull request by skitt**
Release notes: https://v1-15.docs.kubernetes.io/docs/setup/release/notes/

### CODE REVIEW

**Comment by mangelajo** [comment]
Fixed conflict on "DEFINE_string 'k8s_version' '1.15.7' 'Version of K8s to use'" from the depended patch which also modified this.

**Comment by tpantelis** [comment]
https://github.com/submariner-io/shipyard/pull/234 includes this commit so can we close this one in lieu or is there a reason to specifically review/merge this one first?

**Comment by skitt** [comment]
> #234 includes this commit so can we close this one in lieu or is there a reason to specifically review/merge this one first?

I would like to merge and propagate the changes one at a time, it makes it easier to identify required changes when things break.

**Comment by skitt** [comment]
I’ve figured out what’s going wrong here: the service CIDRs are identical in both clusters.

**Pull request merged**
