### PR TITLE
Add a periodic check for updates

### PR DESCRIPTION
**Pull request by skitt**
This catches more pending updates than dependabot, in particular it
identifies updates in projects without releases.

See https://github.com/skitt/shipyard/pull/1/checks?check_run_id=2962467985 for an example run.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
> See https://github.com/skitt/shipyard/pull/1/checks?check_run_id=2962467985 for an example run.

Maybe I'm missing something, but I don't see a sample run there and I don't know how there could be one since the job is being added to the periodic workflow. You could modify the periodic workflow to also run on PRs if you want to show it running there.

**Comment by skitt** [comment]
> > See https://github.com/skitt/shipyard/pull/1/checks?check_run_id=2962467985 for an example run.
> 
> Maybe I'm missing something, but I don't see a sample run there and I don't know how there could be one since the job is being added to the periodic workflow. You could modify the periodic workflow to also run on PRs if you want to show it running there.

That’s what I’d done in my initial submission, to see the job run; the link above was the result. Unfortunately it seems old runs aren’t accessible, or am I missing something?

**Comment by skitt** [comment]
Checks will appear here: https://github.com/skitt/shipyard/pull/2/checks

**Comment by dfarrell07** [comment]
> Checks will appear here: https://github.com/skitt/shipyard/pull/2/checks

Oh wow, such nice output! 

Have you thought about somehow making this fail if there are pending updates (maybe that aren't whitelisted as okay to be behind, like the K8s API)? It's still very cool/useful as it is, just wondering what you're thinking.

**Review by dfarrell07 — APPROVED** [review]

**Comment by skitt** [comment]
> > Checks will appear here: https://github.com/skitt/shipyard/pull/2/checks
> 
> Oh wow, such nice output!
> 
> Have you thought about somehow making this fail if there are pending updates (maybe that aren't whitelisted as okay to be behind, like the K8s API)? It's still very cool/useful as it is, just wondering what you're thinking.

Yeah, I’d thought about that but since we can’t easily ignore certain dependencies, I didn’t want to pursue that right away...

**Comment by skitt** [comment]
This PR is really more about remembering how to do this, with some nice tooling, and having a central place to look for pending updates every now and then (as opposed to me running this locally).

**Comment by dfarrell07** [comment]
Yep, makes sense, that's how I'm using it now (learning/reproducing the magic search you've been doing locally). :+1:

**Review by mkolesnik — COMMENTED** [review]
This doesn't seem to have any ties to Shipyard, what's the significance of checking all the other projects specifically here?

**Comment by skitt** [comment]
> This doesn't seem to have any ties to Shipyard, what's the significance of checking all the other projects specifically here?

It means we run the checks in a single job in a single project, instead of all the Go projects (including Shipyard). I can duplicate the PR across all projects if that makes more sense.

**Review by dfarrell07 — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]

**Comment by dfarrell07** [comment]
Is this ready to merge?

**Comment by skitt** [comment]
> Is this ready to merge?

As far as I’m concerned, it has been for a while.

**Comment by dfarrell07** [comment]
The `Consuming Projects / E2E` job seems to be marked as required, but it shouldn't be I think.

**Comment by dfarrell07** [comment]
All the required jobs are passing, but it's not merging.

**Comment by skitt** [comment]
> All the required jobs are passing, but it's not merging.

According to the block message, this needs one more approving review (from a code owner, I imagine, since there are already two positive reviews).

**Comment by dfarrell07** [comment]
> > All the required jobs are passing, but it's not merging.
> 
> According to the block message, this needs one more approving review (from a code owner, I imagine, since there are already two positive reviews).

I saw that, but GH shows Mike with a "code owner lock" by his name for me. I see now though he doesn't have rights to all the files touched by this PR, like tools.go. I guess that's the blocking UI-driven confusion, not the `Consuming Projects / E2E` being marked as required/skipped until I ran it and none of the individual jobs are marked as required.

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
