### PR TITLE
Bump golangci-lint version from 1.26.0 to 1.28.0

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
@skitt I think the newer version of gosec will flag these in the main repo after the upgrade:

```
pkg/cable/wireguard/getconnections.go:34:29: G601: Implicit memory aliasing in for loop. (gosec)
		w.updateConnectionForPeer(&p, connection)
		                          ^
pkg/controllers/datastoresyncer/datastoresyncer.go:86:49: G601: Implicit memory aliasing in for loop. (gosec)
			endpointName, err := util.GetEndpointCRDName(&endpoint)
			                                             ^
pkg/routeagent/controllers/route/route.go:802:31: G601: Implicit memory aliasing in for loop. (gosec)
				if err = netlink.RouteDel(&route); err != nil {
```

I've already sent https://github.com/submariner-io/submariner/pull/708 to fix the other error the upgrade now flags for the main repo.

**Comment by skitt** [comment]
> @skitt I think the newer version of gosec will flag these in the main repo after the upgrade:

This should be addressed by https://github.com/submariner-io/submariner/pull/709 (but I haven’t checked the new linter).

**Comment by skitt** [comment]
We need a validate-projects label :-)

**Comment by dfarrell07** [comment]
With the exception of the additional gosec issues I highlighted in https://github.com/submariner-io/submariner/pull/709#issuecomment-654178765, this seems to pass with the others repos (I manually tested Operator, Lighthouse, Admiral).

**Comment by mangelajo** [comment]
Thank you Daniel! :)

**Pull request merged**
